package com.tap.backend.audit;

public enum AuditAction {
  UPLOAD_FOLDER_CREATE,
  UPLOAD_FOLDER_FILES,
  UPLOAD_FOLDER_ZIP,
  TRANSLATE_TEXT,
  SUMMARY_PAPER,
  SUMMARY_DOCUMENT,
  AGENT_SUBMIT,
  AGENT_RETRY,
  AGENT_CANCEL,
  ZIP_ORGANIZE_SUBMIT,
  ZIP_ORGANIZE_RETRY,
  ZIP_ORGANIZE_DOWNLOAD
}
